version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: guessing-words-node
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    command: npm run serve
    ports:
      - "8080:8080"